---
- name: install boto
  pip: name=boto

- name: copy config template
  template: >
    src={{ role_path }}/templates/S3BucketCollector/S3BucketCollector.conf
    dest=/etc/diamond/collectors/S3BucketCollector.conf
