---
- name: Install python-pip
  apt: pkg=python-pip state=installed update_cache=yes
  #apt: pkg=python-pip state=installed

- name: Install diamond from pip
  pip: name=diamond version={{ diamond_version }}

- name: Create diamond user
  user: >
    name=diamond
    createhome=no
    append=yes
    groups=root
    system=yes
    state=present
  tags:
    - create_user

- name: Install python-statsd pip module
  pip: name=python-statsd

- name: Configure handlers (pip)
  file: path="{{ diamond_conf_basepath }}/handlers/{{ item }}.conf" state=absent
  with_items:
    - GraphiteHandler
    - StatsdHandler
